name: "Splitter+Timings"
description: "Create a list of tests for gradlew using splitting and timings"
inputs:
  module:
    description: "Module of the project"
    required: true
  node-index:
    description: "Node index of the current matrix"
    required: true
  node-total:
    description: "Node total of the current matrix"
    required: true
  exclude:
    description: "Test files to ignore"
    required: true
outputs:
  tests:
    description: "Tests to be run within gradle"
runs:
  using: "node12"
  main: "dist/index.js"
